services:
  web:
    build: .
    image: forecast_app:latest
    ports:
      - "${HOST_PORT:-3000}:80"
    environment:
      SOLID_QUEUE_IN_PUMA: "true"
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY:?}
    volumes:
      - forecast_app_storage:/rails/storage
      - ./app:/rails/app:ro
      - ./config:/rails/config:ro
      - ./test:/rails/test:ro
      - ./db:/rails/db:ro
    restart: unless-stopped

volumes:
  forecast_app_storage:
